### PR TITLE
Allow tests to be filtered if user is registered

### PR DESCRIPTION
**Pull request by GlynnPhillips**
New filter that will allow subscriber's to be split into two buckets,
the ones that are registered but not paying and the ones that are paying
for a subscription.

```
"filters": [
    {
        "type": "isregistereduser",
        "value": true
    }
]
```

@commuterjoy @wheresrhys @tom-parker There is also a change in [config-vars](https://github.com/Financial-Times/next-config-vars/pull/132/files)

### CODE REVIEW

**Comment by tom-parker** [comment]
Looks good. Has this got some of Rhys multi region code in it too?

We might be able to extend this now to cover more options. If it was a called something like `hasProductCodes` and you pass a single product code or an array of product codes e.g

```
"filters": [
    {
        "type": "hasProductCodes",
        "value": "registered"
    }
]

"filters": [
    {
        "type": "hasProductCodes",
        "value": ["registered", "weekend"]
    }
]
```

Would allow us to target a test at just registered users or registered and weekend etc

**Comment by GlynnPhillips** [comment]
Yeah I appear to have messed up in git somehow and pulled in Rhys last commit.

I agree I saw this in the backlog doc this morning and commented that this could be easily extended to do different product types. I think if we do want to cover more product types that this makes sense to do it now within this PR so we are not changing the API again in the near future from `isregistereduser` to `hasproductcodes`

**Comment by GlynnPhillips** [comment]
@tom-parker now updated for all product types to match your above suggestion.

- Value can be an array or string
- If the value is registered the user cannot have any other product codes
- If the value is NOT registered the user can have other product codes

**Comment by tom-parker** [comment]
Looks good 💯

**Pull request merged**
